### ISSUE TITLE
Delete inactive users

### ISSUE THREAD

**Issue by timhorstmann** [SvenJuergens/disable_beuser#9]
I need the feature, that inactive be_users can also be deleted after a certain amount of time, ideally after they have become inactive. Is this in the scope of this extension? I would contribute in this case.

**Comment by SvenJuergens** [comment]
Hi @timhorstmann, sounds good, maybe as a separate task?
Then you could set all inactive users to inactive with one task and delete them in another task.

**Comment by timhorstmann** [comment]
From my point of view a separate task would have a lot of duplicated code, since the properties are nearly identical. I tried with an abstract parent class but this easily gets confusing with the AdditionalFields class. And it doesn't feel right for me.

Therefore I have 2 pull requests:
- [first one](https://github.com/SvenJuergens/disable_beuser/pull/10) is simply an added event so I can implement the feature of deleting users on my own
- second one is on top of this adding a flag wether a user should be disabled or deleted. Then you can have 2 instances of the task, one for disabling and one for deleting.

If the second pull request does not comply with the idea of the extension, thats fine for me, just let me know.

**Comment by SvenJuergens** [comment]
hi @timhorstmann an event is a good idea :)

but then it should also be a new version, because at the moment TYPO3 9 is still supported, but hope my personal need in this regard is also over in 1-2 months. And yes to delete users, contradicts a little the name of the extension, but find it a very good idea, too So if you still want to make a pull request for a delete feature, I would want to integrate that too.  Other ways like an additional extension would be possible too of course.
